"""empty message

Revision ID: 327948c7295f
Revises: 
Create Date: 2017-12-01 13:44:06.684476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327948c7295f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('in_lab', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_time', sa.DateTime(), nullable=True),
    sa.Column('out_time', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('type_visit', sa.String(length=12), nullable=True),
    sa.Column('visit_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['visit_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('in_time'),
    sa.UniqueConstraint('out_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
