"""adding email validation

Revision ID: 953597b451e6
Revises: b47f678a49f5
Create Date: 2017-10-29 16:29:25.521032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953597b451e6'
down_revision = 'b47f678a49f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
