"""empty message

Revision ID: 9544400f25c0
Revises: 953597b451e6
Create Date: 2017-11-14 23:36:08.022021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9544400f25c0'
down_revision = '953597b451e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('type_visit', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'type_visit')
    # ### end Alembic commands ###
